### ISSUE TITLE
`.ploomber/stats` taking too much space when running 100+ notebooks simultaneously

### ISSUE THREAD

**Issue by avivajpeyi** [ploomber/core#74] opened 2023-07-19 21:38 UTC
Im using ploomber-engine to analyze 100+ notebooks on a computing cluster. I hadnt realised that ploomber-engine creates a folder `.ploomber/stats`, and a `tmp_<blah>.txt` file for each notebook until I started running all the notebooks.This resulted in a memory error (my `/home/user/` directory  where the `.ploomber-engine` folder is stored has a restriction of 10GB).**Is it possible to customize the dir/path of these temp files?**

**Comment by edublancas** [comment] 2023-07-20 13:46
Ok, I transferred this issue to the `ploomber-core` repository.

tmp fix: you can downgrade to [ploomber-core](https://github.com/ploomber/core/blob/main/CHANGELOG.md#0213-2023-06-27) 0.2.12 (and still use the latest version of ploomber-engine), it won't generate the temp files.

we'll look into this

**Comment by edublancas** [comment] 2023-07-20 14:06
I took a look at the code, and the files are immediately deleted [after creation](https://github.com/ploomber/core/blob/f0d346a49e0578f93965a39f6c6134831424be7b/src/ploomber_core/config.py#L159), and they're empty files. So the problem isn't disk space but that too many files are created simultaneously. thoughts? do you think this is what's happening?

possible solutions:

- do not write the tmp file if the config file already exists (there's still a chance that the filesystem was writable before and it's not now but probably a small chance)
- check if filesystem is writable without creating a temp file https://stackoverflow.com/a/2113511/709975

**Comment by avivajpeyi** [comment] 2023-07-27 00:11
> the problem isn't disk space but that too many files are created simultaneously.

Yes, I think the issue is relating to the number of files created rather than the size. 

Another solution would be to allow the user to customize the dir where this stuff is done (eg if I chuck this in scratch space then i wont face this issue probably)

**Comment by edublancas** [comment] 2023-07-27 03:54
ok, we'll investigate some of these approaches and decide.

the team is full at the moment so I'll assign this when we some time, but feel free to open a PR.

I'd say this is the most desirable option:

> check if filesystem is writable without creating a temp file https://stackoverflow.com/a/2113511/709975

**Closed** 2024-05-02 20:04 UTC
Labels: stash
