### ISSUE TITLE
config fails to initialize

### ISSUE THREAD

**Issue by edublancas** [ploomber/core#12] opened 2022-08-15 19:08 UTC
I saw this in this [example](https://sklearn-evaluation.readthedocs.io/en/latest/user_guide/nbdb.html):

```
/home/docs/checkouts/readthedocs.org/user_builds/sklearn-evaluation/conda/latest/lib/python3.8/site-packages/ploomber_core/config.py:31: UserWarning: Error loading '/home/docs/.ploomber/stats/config.yaml': 'NoneType' object has no attribute 'get'

reverting to default values
  warnings.warn(f'Error loading {str(path)!r}: {e}\n\n'
/home/docs/checkouts/readthedocs.org/user_builds/sklearn-evaluation/conda/latest/lib/python3.8/site-packages/ploomber_core/config.py:31: UserWarning: Error loading '/home/docs/.ploomber/stats/uid.yaml': 'NoneType' object has no attribute 'get'

reverting to default values
  warnings.warn(f'Error loading {str(path)!r}: {e}\n\n'
/home/docs/checkouts/readthedocs.org/user_builds/sklearn-evaluation/conda/latest/lib/python3.8/site-packages/ploomber_core/config.py:31: UserWarning: Error loading '/home/docs/.ploomber/stats/config.yaml': 'NoneType' object has no attribute 'get'

reverting to default values
```

looks like the config fails to  initialize and the file is never created

Maybe this is the right thing to do and it's just that some logic is wrong. I updated this package so it doesn't call posthog when it detects it's running on readthedocs (which we use to generate documentation) - perhaps that's causing the warning?

**Comment by edublancas** [comment] 2022-08-15 22:30
hint to reproduce: let's simulate that something is running on READTHEDOCS by setting the [env variable](https://github.com/ploomber/core/blob/47e2db45740484ad862dc42c496f7c48f2c9f2f7/src/ploomber_core/telemetry/telemetry.py#L263) , ensure the `~/.ploomber` directory does not exist and then see if running some ploomber example triggers that warning

**Comment by yafimvo** [comment] 2022-08-16 12:27
I've cloned this repo and executed the code according to the example and the steps to reproduce (with READTHEDOCS as env var).

I got the same warning (6 times)
`
reverting to default values
  warnings.warn(f'Error loading {str(path)!r}: {e}\n\n'
C:\Users\User\Anaconda3\envs\ploomber-core\lib\site-packages\ploomber_core\config.py:31: UserWarning: Error loading 'C:\\Users\\User\\.ploomber\\stats\\config.yaml': 'NoneType' object has no attribute 'get'
`

Working directory
![image](https://user-images.githubusercontent.com/103026689/184873140-2b7d6ade-9f71-4427-9277-386009b89d85.png)


I ran the same example using the serial executor and didn't get this warning.

The number of newly created files is the same in both, parallel and serial.


It seems the warning comes from [here ](https://github.com/ploomber/core/blob/0c83ad4dc7b27643764e16538731c85114cbaf3b/src/ploomber_core/config.py#L48) when content is 'None' (and it happens only when using parallel)

**Comment by edublancas** [comment] 2022-08-16 13:38
does the error still happen if you don't set the READTHEDOCS?

any conclusions why it happens with parallel? You might need to add some logging to debug this.

**Comment by edublancas** [comment] 2022-08-16 13:48
so I noticed something, the error is saying the object is None, this happens when the YAML is an empty file. So looks like the file exists, but it's empty. maybe a race condition since multiple processes are trying to save the same file?

**Comment by yafimvo** [comment] 2022-08-17 14:57
The problem persists even without setting READTHEDOCS.
I debugged it in Parallel and Serial with some logs and it seems like it is a race condition situation (i.e the number of these warning is changing from time to time).

I'm not sure where to begin to fix this. (I thought it will be in `Parallel` class [here ](https://github.com/ploomber/ploomber/blob/38b8bc485ff82df7a019326979557b95c1371761/src/ploomber/executors/parallel.py#L241) but it never gets there).

**Comment by edublancas** [comment] 2022-08-17 17:39
I think this might be a sklearn-evaluation-specific problem and have an idea of how to debug. Let me try something quick in the next few days and I'll post an update here

**Comment by edublancas** [comment] 2022-08-19 19:37
update: this looks like a general problem. I thought it was only happening on sklearn-evaluation but it also happens when using ploomber. so please @yafimvo help us with this!

**Comment by yafimvo** [comment] 2022-08-24 14:59
I added a lock to TaskBuildWrapper

```
    def __call__(self, lock, *args, **kwargs):
        with lock:
            try:
                output = self.task._build(**kwargs)
                return output
            except Exception as e:
                return Message(task=self.task,
                               message=_format.exception(e), obj=e)
```

So we can use it like this

```
future = pool.submit(TaskBuildWrapper(task), lock, **task_kwargs)
```


It seems to fix these warnings.

Some notes:
1. I'm not sure how to auto-test this
2. This change doesn't break existing tests
3. If this is an acceptable solution I'll create a PR to Ploomber repo and not this one

**Comment by edublancas** [comment] 2022-08-26 01:11
what is this lock doing? wouldn't it interfere with the parallel executor logic? i.e.g, if a task acquires a lock, other tasks won't run simultaneously?

did you find out why this is happening? It seems to me that the error is in this package, and a fix should be applied here

**Comment by yafimvo** [comment] 2022-08-28 12:44
> what is this lock doing? wouldn't it interfere with the parallel executor logic? i.e.g, if a task acquires a lock, other tasks won't run simultaneously?

This lock should protect config.yaml and uid.yaml from being changed by other tasks. Even though it passed the existing tests, this implementation locks the entire task, so yes, I think this may affect the parallel executor (the lock will be released once the task has been completed).

> did you find out why this is happening? It seems to me that the error is in this package, and a fix should be applied here

I think it happens when 2 tasks run simultaneously, one creates the configuration file (config.yaml/uid.yaml), while the other task is trying to read from it.

I think it completes the tasks successfully since we have this exception handler to re-load content from the dictionary

```
            try:
                content = self._load_from_file()
                loaded = True
            except Exception as e:
                warnings.warn(f'Error loading {str(path)!r}: {e}\n\n'
                              'reverting to default values')
                loaded = False
                content = self._get_data()
```

Can we just use the `content = self._get_data()` instead of reading from the file?

**Comment by edublancas** [comment] 2022-08-28 21:14
> I think this may affect the parallel executor (the lock will be released once the task has been completed).

this is a big drawback for users, so we'll have to find another solution

> Can we just use the content = self._get_data() instead of reading from the file?

ah. yes! I started overcomplicating, thinking we'd need a more elaborate solution, but you're right! This problem happens because the first process doesn't see the file, so it proceeds to create it, while the second sees the file but not its contents (since the writing operation is still in progress). However, under that scenario, it's safe to load `self._get_data`, since it'll load the default values (which are the same values that we're writing).

I wanted to convince myself and tested the solution. I think it works but please review #12

**Comment by yafimvo** [comment] 2022-08-29 07:52
Question: I noticed that configuration files might differ from task to task. When loading data directly from a file, are we sure it's the right configuration for this task?

**Closed** 2022-08-29 13:37 UTC
Labels: low-effort, high-priority

**Comment by edublancas** [comment] 2022-08-29 13:38
> Question: I noticed that configuration files might differ from task to task. When loading data directly from a file, are we sure it's the right configuration for this task?

Yes, Config is an abstract class with an abstract `path` method. Concrete classes define this method which returns the name of the file they're using:

https://github.com/ploomber/core/blob/e6e5cc34613fb950026bc4981b8265bbdd1f9980/src/ploomber_core/config.py#L116
